package co.electriccoin.zcash.ui.common.repository

import kotlinx.coroutines.flow.MutableStateFlow

/**
 * The unsigned PCZT bytes built for a Keystone batch-signing attempt (the note-split, if needed,
 * plus every schedule transfer), retained so [applyKeystoneBatchSignatures]'s caller can match the
 * device's signatures back to the originals it built them from — these are Rust-generated byte
 * blobs, too large/inappropriate to round-trip through Compose Navigation's serialized nav args.
 *
 * When the full batch is larger than one Keystone QR round can safely hold
 * (the `KeystoneSigningRoundBudget` returned by `sdk.keystoneSigningRoundBudget()`, see
 * `KeystoneBatchChunking.kt`), it's split into multiple rounds via
 * `keystoneBatchRoundSlice` — [roundIndex] tracks which round is currently in flight (0-based),
 * and [accumulatedSplitSigned]/[accumulatedTransferSigned] carry every already-completed round's
 * results forward so the final round can hand the *whole* signed set to
 * `storeSignedNoteSplitPczt`/`storeSignedSchedulePczts`, not just its own slice. Defaulted so the
 * common single-round case (and existing tests) are unaffected.
 */
data class PendingKeystoneMigrationPczts(
    val requestId: ByteArray,
    val splitUnsignedPczt: ByteArray?,
    val transferUnsignedPczts: List<Pair<Long, ByteArray>>,
    /**
     * Preparation transactions BEYOND the first layer-0 split (engine id order) — the rest of the
     * note-split tree, all built (and pre-signable) at commit. Their signed results go through the
     * kind-agnostic storeSignedSchedulePczts alongside the transfers; only the first split keeps
     * the immediate-broadcast storeSignedNoteSplitPczt path.
     */
    val prepUnsignedPczts: List<Pair<Long, ByteArray>> = emptyList(),
    val roundIndex: Int = 0,
    val accumulatedSplitSigned: ByteArray? = null,
    val accumulatedPrepSigned: List<Pair<Long, ByteArray>> = emptyList(),
    val accumulatedTransferSigned: List<Pair<Long, ByteArray>> = emptyList(),
)

/**
 * Transient, in-memory handoff of [PendingKeystoneMigrationPczts] between the Keystone sign screen
 * (which builds the unsigned PCZTs and the QR) and the scan screen (which applies the device's
 * signatures back to them) — sibling to [PendingMigrationScheduleRepository], same "not persisted,
 * re-enter from Confirm Transfer Plan on process death" contract.
 *
 * The PCZTs are stored together with the [accountKeyId] of the account that set them. [get]
 * returns `null` and clears the stored value when the caller's key id does not match the stored
 * one, preventing an account switch mid-flow from feeding one account's unsigned PCZTs (which
 * carry that account's private key material) into another account's scan path.
 */
interface PendingKeystoneMigrationPcztsRepository {
    fun set(accountKeyId: String, pczts: PendingKeystoneMigrationPczts)

    fun get(accountKeyId: String): PendingKeystoneMigrationPczts?

    fun clear()
}

class PendingKeystoneMigrationPcztsRepositoryImpl : PendingKeystoneMigrationPcztsRepository {
    private val pending = MutableStateFlow<Pair<String, PendingKeystoneMigrationPczts>?>(null)

    override fun set(accountKeyId: String, pczts: PendingKeystoneMigrationPczts) {
        pending.value = accountKeyId to pczts
    }

    override fun get(accountKeyId: String): PendingKeystoneMigrationPczts? {
        val current = pending.value ?: return null
        return if (current.first == accountKeyId) current.second else null
    }

    override fun clear() {
        pending.value = null
    }
}
